import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/provider";
import i18n from "@/i18n";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});




// Site configuration
const siteConfig = {
  name: "Riva App",
  description: "Transform your ideas into reality with cutting-edge software solutions. We build the future with innovation.",
  url: "https://siliconinfiniti.com",
  ogImage: "https://siliconinfiniti.com/og-image.jpg",
  links: {
    twitter: "https://twitter.com/siliconinfiniti",
    github: "https://github.com/siliconinfiniti",
    linkedin: "https://linkedin.com/company/siliconinfiniti",
  },
};

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.name + " - Delivery App",
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: [
    "food delivery",
    "online delivery",
    "restaurant delivery",
    "fast delivery",
    "local delivery",
    "order food online",
    "meal delivery",
    "grocery delivery",
    "delivery app",
    "on demand delivery",
    "restaurant ordering",
    "food ordering app",
    "توصيل الطعام",
    "طلب طعام اونلاين",
    "تطبيق توصيل",
    "توصيل سريع",
    "توصيل مطاعم",
    "طلب وجبات",
    "توصيل بقالة",
    "خدمة التوصيل",
    "اطلب طعامك",
    "توصيل محلي"
  ],
  authors: [
    {
      name: "Riva App",
      url: siteConfig.url,
    },
  ],
  creator: "Riva App",
  publisher: "Riva App",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    alternateLocale: ["ar_SA"],
    url: siteConfig.url,
    title: siteConfig.name,
    description: siteConfig.description,
    siteName: siteConfig.name,
    images: [
      {
        url: siteConfig.ogImage,
        width: 1200,
        height: 630,
        alt: siteConfig.name,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.name,
    description: siteConfig.description,
    images: [siteConfig.ogImage],
    creator: "@siliconinfiniti",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
};


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const organizationSchema = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "Riva App",
    url: siteConfig.url,
    logo: `${siteConfig.url}/logo.png`,
    description: siteConfig.description,
    address: {
      "@type": "PostalAddress",
      addressLocality: "Riyadh",
      addressCountry: "SA",
    },
    contactPoint: {
      "@type": "ContactPoint",
      telephone: "+966501234567",
      contactType: "customer service",
      email: "hello@siliconinfiniti.com",
      availableLanguage: ["English", "Arabic"],
    },
    sameAs: [
      siteConfig.links.twitter,
      siteConfig.links.github,
      siteConfig.links.linkedin,
    ],
  };
  return (
    <html lang="en">

      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(organizationSchema),
          }}
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>

      </body>
    </html>
  );
}
